version: '3'

networks:
  transins:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16

services:
  transins-marian-de-en-mono-opus:
    image: 'dfki/transins-marian:1.0.0'
    networks:
      - transins
    container_name: transins-marian-de-en-mono-opus
    restart: always
    volumes:
      - './src/main/resources/marian-nmt/de-en-mono-opus:/TransIns-marian/config:ro'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  transins-marian-en-de-mono-opus:
    image: 'dfki/transins-marian:1.0.0'
    networks:
      - transins
    container_name: transins-marian-en-de-mono-opus
    restart: always
    volumes:
      - './src/main/resources/marian-nmt/en-de-mono-opus:/TransIns-marian/config:ro'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  transins-marian-de-fr-mono-opus:
    image: 'dfki/transins-marian:1.0.0'
    networks:
      - transins
    container_name: transins-marian-de-fr-mono-opus
    restart: always
    volumes:
      - './src/main/resources/marian-nmt/de-fr-mono-opus:/TransIns-marian/config:ro'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]

  transins-marian-fr-de-mono-opus:
    image: 'dfki/transins-marian:1.0.0'
    networks:
      - transins
    container_name: transins-marian-fr-de-mono-opus
    restart: always
    volumes:
      - './src/main/resources/marian-nmt/fr-de-mono-opus:/TransIns-marian/config:ro'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]

  transins-prepost:
    image: 'dfki/transins-prepost:1.0.0'
    networks:
      - transins
    container_name: transins-prepost
    restart: always
    volumes:
      - './src/main/resources/prepostprocessing:/TransIns-prepost/config:ro'

  transins-server:
    depends_on:
      - transins-marian-de-en-mono-opus
      - transins-marian-en-de-mono-opus
      - transins-marian-de-fr-mono-opus
      - transins-marian-fr-de-mono-opus
      - transins-prepost
    image: 'dfki/transins-server:1.0.0'
    networks:
      - transins
    container_name: transins-server
    restart: always
    ports:
      - '7777:7777'
