# by default, ignore everything
**

# allowed files and folders
!/pom.xml
!/src/main/java/**
!/src/main/resources/okapi
!src/main/resources/*.properties
!src/main/resources/logback.xml
!src/main/resources/transIns.cfg
!src/main/web/**
