version: '3'

networks:
  transins:

services:
  transins-marian-de-en-bi:
    image: 'dfki/transins-marian:0.0.1'
    networks:
      - transins
    container_name: transins-marian-de-en-bi
    restart: always
    volumes:
      - './src/main/resources/marian-nmt/de-en-bi:/TransIns-marian/config:ro'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  transins-marian-de-es-mono:
    image: 'dfki/transins-marian:0.0.1'
    networks:
      - transins
    container_name: transins-marian-de-es-mono
    restart: always
    volumes:
      - './src/main/resources/marian-nmt/de-es-mono:/TransIns-marian/config:ro'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  transins-marian-es-de-mono:
    image: 'dfki/transins-marian:0.0.1'
    networks:
      - transins
    container_name: transins-marian-es-de-mono
    restart: always
    volumes:
      - './src/main/resources/marian-nmt/es-de-mono:/TransIns-marian/config:ro'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  transins-marian-de-fr-mono:
    image: 'dfki/transins-marian:0.0.1'
    networks:
      - transins
    container_name: transins-marian-de-fr-mono
    restart: always
    volumes:
      - './src/main/resources/marian-nmt/de-fr-mono:/TransIns-marian/config:ro'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]

  transins-marian-fr-de-mono:
    image: 'dfki/transins-marian:0.0.1'
    networks:
      - transins
    container_name: transins-marian-fr-de-mono
    restart: always
    volumes:
      - './src/main/resources/marian-nmt/fr-de-mono:/TransIns-marian/config:ro'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]

  transins-prepost:
    image: 'dfki/transins-prepost:0.0.1'
    networks:
      - transins
    container_name: transins-prepost
    restart: always
    volumes:
      - './src/main/resources/prepostprocessing:/TransIns-prepost/config:ro'

  transins-server:
    depends_on:
      - transins-marian-de-en-bi
      - transins-marian-de-es-mono
      - transins-marian-es-de-mono
      - transins-marian-de-fr-mono
      - transins-marian-fr-de-mono
      - transins-prepost
    image: 'dfki/transins-server:0.0.1'
    networks:
      - transins
    container_name: transins-server
    restart: always
    ports:
      - '7777:7777'
