= TransIns - Document Translation with Advanced Markup Re-Insertion =
:nofooter:

V1.0.0

written by Jörg Steffen
DFKI MLT-Lab

Email: steffen@dfki.de

== Overview
TransIns uses the https://okapiframework.org/[Okapi] framework to parse documents of supported formats (currently MS Office, OpenOffice and html) into a representation that preserves the document markup and allows access to the document's text content on a sentence level. The sentences, without the markup, are translated using translation models trained and provided by the neural machine translation framework https://marian-nmt.github.io/[MarianNMT]. Afterwards, the markup is re-inserted into the translated sentences based on token alignments. Finally, a translated document is provided in the original format.

We implement the following strategies for re-inserting markup into the translated sentence using the tokens' alignments:

* `MTRAIN`: A strategy assigning markup to the token next to it, as described in this https://www.aclweb.org/anthology/W17-4804/[paper] of Matthias Müller and implemented in the Zurich NLP https://github.com/ZurichNLP/mtrain/blob/master/mtrain/preprocessing/reinsertion.py#L315[mtrain] Python package
* `MTRAIN_IMPROVED`: An improved version of the MTRAIN strategy
* `COMPLETE_MAPPING`: A strategy assigning markup to *all* tokens in the markup's range

== REST API

TransIns provides a RESTful API that allows to query the translation service in an asynchronous way.

The REST endpoint for sending a document to translate is `/transins/translate`. The query has to be sent as POST request encoded as `multipart/form-data` with the following fields:

* `file` the file name of the document to translate
* `sl` the source language, i.e. the language of the above document
* `tl` the target language, i.e. the language to translate the document to
* `enc` the encoding of the document; the translated document will use the same encoding
* `strategy` the markup re-insertion strategy to use; possible values are `MTRAIN`, `MTRAIN_IMPROVED` and `COMPLETE_MAPPING` (default if strategy is not provided)

If successful, the service returns a token which is required to retrieve the translated document with a second query. That query has to be sent as GET request to the `/transins/getTranslation` REST endpoint. It requires the token as path parameter. Please note that it is not guaranteed that the translated document can be retrieved immediately, as the translation may take some time. If the translation is not yet available, the second call returns a `202` HTTP response code.

If required, the token can also be used to cancel a translation and/or force the deletion of all associated files on the server. A delete query has to be sent as DELETE request to the `/transins/deleteTranslation` REST endpoint with the token as path parameter.

To test the REST service, use the https://curl.haxx.se/[curl] and https://www.gnu.org/software/wget/[wget] tools.

A POST query to translate an MS Office document `MyDoc.docx` from German to French sent to a TransIns service running on port 7777 at localhost would look like this:
```
curl -i -X POST -H "Content-Type: multipart/form-data" \
  -F "file=@MyDoc.docx" -F "sl=de" -F "tl=fr" -F "enc=windows-1252" \
  -F "strategy=COMPLETE_MAPPING" \
  localhost:7777/transins/translate
```

This returns a token `cbVHK6U2oJIO8hCPvU4LR6dL3FSt2oU0nw9VBbFo` that must be used in the second GET query to retrieve the translated document:

```
wget -S --content-disposition \
  localhost:7777/transins/getTranslation/cbVHK6U2oJIO8hCPvU4LR6dL3FSt2oU0nw9VBbFo
```

In order to delete the files on the server, use this DELETE query:
```
curl -i -X DELETE \
  localhost:7777/transins/deleteTranslation/cbVHK6U2oJIO8hCPvU4LR6dL3FSt2oU0nw9VBbFo
```
